import NextHead from 'next/head';

/**
 * Head component.
 * 
 * @returns React component. 
 */
const Head = (): JSX.Element =>
    <NextHead>
        <title>=nil; Foundation</title>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#222222" />
        <meta name="author" content="=nil; Foundation" />
        <meta name="copyright" content="=nil; Foundation" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </NextHead>;

export default Head;
