// Interface automatically generated by schemas-to-ts

export interface Paragraphs {
  Paragraph?: string
}
export interface Paragraphs_Plain {
  Paragraph?: string
}

export interface Paragraphs_NoRelations {
  Paragraph?: string
}
